version: "3"
services:

  hnn:
    image: jonescompneurolab/hnn
    container_name: hnn_container
    hostname: hnn-container
    environment:
      XAUTHORITY: "/home/hnn_user/.Xauthority"
      DISPLAY: $DISPLAY
      SYSTEM_USER_DIR: $HOME
    volumes:
      - "$XAUTHORITY:/home/hnn_user/.Xauthority"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME:$HOME"
    command: /home/hnn_user/start_hnn.sh
