version: "3"
services:

  hnn:
    image: jonescompneurolab/hnn
    container_name: hnn_container
    hostname: hnn-container
    ports:
      - "22"
    environment:
      XAUTHORITY: "/home/hnn_user/.Xauthority"
      DISPLAY: "host.docker.internal:0"
      SYSTEM_USER_DIR: $HOME
    volumes:
      - "$XAUTHORITY:/home/hnn_user/.Xauthority"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME:$HOME"
    command: "sudo /start_ssh.sh"
